# Preserved flake outputs: cargo-mem-guard, cargo-mem-guard-unwrapped
# (packages); cargo-mem-guard-tests (checks).
{
  pkgs,
  lib,
  craneLib,
}:
let
  # Workspace member. Isolated fileset root so crane never loads the
  # monorepo Cargo.toml (that would compile the whole workspace).
  # In-repo the crate inherits workspace.package/lints; this copy is a
  # one-member workspace with the same inherit keys plus a tiny lock
  # (no crates.io deps). Crate-local clippy.toml stays nearest.
  memGuardRoot = ../crates/codegen/cargo-mem-guard;

  memGuardFiles = lib.fileset.toSource {
    root = memGuardRoot;
    fileset = lib.fileset.unions [
      (memGuardRoot + /Cargo.toml)
      (memGuardRoot + /clippy.toml)
      (memGuardRoot + /src)
    ];
  };

  memGuardSrc = pkgs.runCommand "cargo-mem-guard-crane-src" { } ''
    mkdir -p $out/cargo-mem-guard
    cp -R ${memGuardFiles}/. $out/cargo-mem-guard/
    chmod -R u+w $out
    cat > $out/Cargo.toml <<'EOF'
[workspace]
resolver = "2"
members = ["cargo-mem-guard"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"

[workspace.lints.clippy]
EOF
    cat > $out/Cargo.lock <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "cargo-mem-guard"
version = "0.1.0"
EOF
  '';

  memGuardCrate = craneLib.crateNameFromCargoToml {
    cargoToml = memGuardRoot + /Cargo.toml;
  };

  memGuardCommonArgs = {
    inherit (memGuardCrate) pname version;
    src = memGuardSrc;
    strictDeps = true;
    # Pure std; no openssl / dbus / protoc.
    meta = {
      description = "Memory-aware cargo wrapper for constrained CI runners";
      homepage = "https://github.com/SurmountSystems/grok-oss";
      license = lib.licenses.asl20;
      mainProgram = "cargo-mem-guard";
      platforms = lib.platforms.unix;
    };
  };

  # Install package only (no unit tests here). Tests live solely in
  # checks.cargo-mem-guard-tests so free GHA / mem-guard does not pay
  # for the suite twice (package doCheck + separate check attr).
  cargo-mem-guard-unwrapped = craneLib.buildPackage (
    memGuardCommonArgs
    // {
      doCheck = false;
    }
  );

  # Unit tests as the single flake check for this crate.
  cargo-mem-guard-tests = craneLib.cargoTest (
    memGuardCommonArgs
    // {
      cargoArtifacts = craneLib.buildDepsOnly memGuardCommonArgs;
    }
  );

  # Bake mold into the runtime closure on Linux so CARGO_MEM_USE_MOLD
  # works without relying on the ambient host PATH.
  cargo-mem-guard =
    if pkgs.stdenv.isLinux then
      pkgs.symlinkJoin {
        name = "${memGuardCrate.pname}-${memGuardCrate.version}";
        paths = [ cargo-mem-guard-unwrapped ];
        nativeBuildInputs = [ pkgs.makeWrapper ];
        postBuild = ''
          wrapProgram $out/bin/cargo-mem-guard \
            --prefix PATH : ${lib.makeBinPath [ pkgs.mold ]} \
            --set-default CARGO_MEM_USE_MOLD 1
        '';
        meta = cargo-mem-guard-unwrapped.meta // {
          description = "${cargo-mem-guard-unwrapped.meta.description} (with mold)";
        };
      }
    else
      cargo-mem-guard-unwrapped;
in
{
  inherit
    cargo-mem-guard
    cargo-mem-guard-unwrapped
    cargo-mem-guard-tests
    ;
}
