# Preserved flake outputs: grok-nix-helper, grok-nix-helper-unwrapped
# (packages); grok-nix-helper-tests (checks).
#
# Workspace member. Isolated fileset root so crane never loads the
# monorepo Cargo.toml. Pure std; no writeShellApplication of the old
# helper .sh files. In-repo the crate inherits workspace.package/lints;
# this copy is a one-member workspace with the same inherit keys plus a
# tiny lock (no crates.io deps). Crate-local clippy.toml stays nearest.
{
  pkgs,
  lib,
  craneLib,
}:
let
  helperRoot = ../crates/codegen/grok-nix-helper;

  helperFiles = lib.fileset.toSource {
    root = helperRoot;
    fileset = lib.fileset.unions [
      (helperRoot + /Cargo.toml)
      (helperRoot + /clippy.toml)
      (helperRoot + /src)
    ];
  };

  helperSrc = pkgs.runCommand "grok-nix-helper-crane-src" { } ''
    mkdir -p $out/grok-nix-helper
    cp -R ${helperFiles}/. $out/grok-nix-helper/
    chmod -R u+w $out
    cat > $out/Cargo.toml <<'EOF'
[workspace]
resolver = "2"
members = ["grok-nix-helper"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"

[workspace.lints.clippy]
EOF
    cat > $out/Cargo.lock <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "grok-nix-helper"
version = "0.1.0"
EOF
  '';

  helperCrate = craneLib.crateNameFromCargoToml {
    cargoToml = helperRoot + /Cargo.toml;
  };

  helperCommonArgs = {
    inherit (helperCrate) pname version;
    src = helperSrc;
    strictDeps = true;
    meta = {
      description = "Nix CI helpers and git recon: retry, hermetic PATH, process-pin assert, put-history, import, join";
      homepage = "https://github.com/SurmountSystems/grok-oss";
      license = lib.licenses.asl20;
      mainProgram = "grok-nix-helper";
      platforms = lib.platforms.unix;
    };
  };

  # Install package only (no unit tests here). Tests live solely in
  # checks.grok-nix-helper-tests so the package graph does not pay
  # for the suite twice (package doCheck + separate check attr).
  grok-nix-helper-unwrapped = craneLib.buildPackage (
    helperCommonArgs
    // {
      doCheck = false;
    }
  );

  grok-nix-helper-tests = craneLib.cargoTest (
    helperCommonArgs
    // {
      cargoArtifacts = craneLib.buildDepsOnly helperCommonArgs;
    }
  );

  grok-nix-helper = grok-nix-helper-unwrapped;
in
{
  inherit
    grok-nix-helper
    grok-nix-helper-unwrapped
    grok-nix-helper-tests
    ;
}
